Buffer: Buffer.java
  javac -o Buffer Buffer.java

Consumer: Consumer.java
  javac -o Consumer Consumer.java

Coordinator: Coordinator.java
  javac -o Coordinator Coordinator.java

Producer: Producer.java
  javac -o Producer Producer.java

clean:
  rm Buffer Consumer Coordinator Producer