CharacterReader: CharacterReader.c
  gcc -o CharacterReader CharacterReader.c

Fibb: Fibb.c
  gcc -o Fibb Fibb.c -lrt

Prime: Prime.c
  gcc -o Prime Prime.c -lrt

Total: Total.c
  gcc -o Total Total.c -lrt

Starter: Starter.c Fibb Prime Total CharacterReader
  gcc -o Starter Starter.c -lrt

clean:
  rm CharacterReader Fibb Prime Total Starter