Fibb: Fibb.c
  gcc -o Fibb Fibb.c

Prime: Prime.c
  gcc -o Prime Prime.c

Total: Total.c
  gcc -o Total Total.c

Starter: Starter.c Fibb Prime Total
  gcc -o Starter Starter.c

clean:
  rm Fibb Prime Total Starter